Add option to use NetCDF output instead of binary for point output
NOAA-EMC/WW3 pull request #1230
Opened 2024-05-13 16:46 UTC by JessicaMeixner-NOAA

# Pull Request Summary
Add a switch BIN2NC which will write a NetCDF file instead of a binary file for point output. 

## Description
When using BIN2NC, the point output will now be written in NetCDF from ww3_shel or ww3_multi.  The exes for output post-processing will be able to read these files.  Some notes: 
* ww3_ounp is still necessary.  While we can add at a future date direction and frequency so that programs such as ww3_bounc could use this without post-processing with ww3_ounf, there are many options and formats of variables that we likely do not want to be converting between in the model output.  Therefore, at this time, we are not replacing ww3_ounp.  There is room for future enhancement to reduce the need for ww3_ounp for some applications. 
* A switch was used instead of a namelist option because I suspect we will eventually remove binary, but in the meantime having a switch still allows those who wish to run without NetCDF that option.  I thought this was the simplest approach, but it's certainly not the only possibility and could be another future place for improvement. 

Co-authors are @edwardhartnett and @MatthewMasarik-NOAA 

Please also include the following information: 
* Mention any labels that should be added  _new feature_
* Are answer changes expected from this PR? While the format of the output will change and regtests that have added this feature will change, the other files do not change.  

### Issue(s) addressed

- fixes #682

### Commit Message
Add option to use NetCDF output instead of binary for point output 

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [x] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [x] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested? With matrix.  Additionally, I hard-coded the switch option to always be on and then ran all of the regression tests using the NetCDF option (see branch: https://github.com/JessicaMeixner-NOAA/WW3/tree/feature/pointbinary2nc_hardcoded).  Output of this branch matrix comp is also shared below.  
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes, new tests were added. 
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? Yes hera intel  (on this branch, plus the hard-coded branch). 
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)

New tests: 
ww3 ww3_tp2.2/work_PR1_MPI_BIN2NC 
And updates to ww3_ufs1.1 unstructured tests as they will now use this feature.  Note the results do not chnage, just binary -> netcdf for the points, and the switch file in the netcdf output. 

* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

I ran two sets of tests, one from this branch compared with develop: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (11 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.2/./work_PR1_MPI_BIN2NC                     (directory not found)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.1/./work_unstr_b                     (1 files differ)
ww3_ufs1.1/./work_unstr_a                     (1 files differ)
ww3_ufs1.1/./work_unstr_c                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/15297702/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/15297703/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/15297704/matrixDiff.txt)

And then I ran tests hard-coding the option to use BIN2NC by default (https://github.com/JessicaMeixner-NOAA/WW3/tree/feature/pointbinary2nc_hardcoded) to ensure all the various combinations were tested and ignoring "0 diffs" in the output the changes are as expected as well: 

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (21 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (13 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (13 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (13 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (3 files differ)
ww3_tp2.2/./work_PR1_MPI_BIN2NC                     (directory not found)
ww3_ufs1.1/./work_unstr_b                     (1 files differ)
ww3_ufs1.1/./work_unstr_a                     (1 files differ)
ww3_ufs1.1/./work_unstr_c                     (1 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```
* note the ww3_ufs1.1/./work_unstr_* cases are because the switch file changed in the NetCDF output. 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/15297692/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/15297693/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/15297694/matrixDiff.txt)

2024-05-13 17:02 UTC, MatthewMasarik-NOAA commented
@JessicaMeixner-NOAA it's great to see this worked PR'd!  I'll start reviewing.

2024-05-14 15:23 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi Great question about timings on binary versus NetCDF.  Just using the regression tests you can see the differences in "Total Run Time" here: 
[Total Run Time - Sheet1.csv](https://github.com/NOAA-EMC/WW3/files/15310567/Total.Run.Time.-.Sheet1.csv)

I'm not seeing anything systematic between the two.  This also combines all the run times for all of the programs, which is probably not the best way to compare.  If you have some specific ideas on tests you'd be interested in seeing, perhaps on a longer time scale, please let me know.

2024-05-14 15:37 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi I updated my last comment.  I don't see systematic differences in timing with using netcdf versus binary, but I'm also not sure these are the best tests to confirm this.  Let me know if you'd like to see something specific timing wise and I'll share if I get any additional results.

2024-05-22 17:38 UTC, JessicaMeixner-NOAA commented
@ukmo-ccbunney @mickaelaccensi just wanted to see if you'd had a chance to look at this at all and if you had any questions.

2024-05-23 10:33 UTC, ukmo-ccbunney reviewed
I have tried running the new ww3_tp2.2 regression test and get the following error:
```
  WAVEWATCH III calculating for 2022/06/06 04:30:00 UTC at 11:25:07
  WAVEWATCH III calculating for 2022/06/06 05:00:00 UTC at 11:25:07
  WAVEWATCH III calculating for 2022/06/06 05:30:00 UTC at 11:25:07
  WAVEWATCH III calculating for 2022/06/06 06:00:00 UTC at 11:25:08
  WAVEWATCH III calculating for 2022/06/06 06:30:00 UTC at 11:25:08
application called MPI_Abort(MPI_COMM_WORLD, 21) - process 1
  *** WAVEWATCH III ERROR IN W3IOPO :
  LINE NUMBER         1556
  NETCDF ERROR MESSAGE: 
 Error: No such file or directory
  *** WAVEWATCH III ERROR IN W3IOPO :
  LINE NUMBER         1773
  NETCDF ERROR MESSAGE: 
 Error: No such file or directory
  *** WAVEWATCH III ERROR IN W3IOPO :
 Nonzero return at end of W3IOPON
 Error: No such file or directory
```

I am investigating.

2024-05-23 11:42 UTC, ukmo-ccbunney commented
> I have tried running the new ww3_tp2.2 regression test and get the following error:
> 
> ```
>   WAVEWATCH III calculating for 2022/06/06 04:30:00 UTC at 11:25:07
>   WAVEWATCH III calculating for 2022/06/06 05:00:00 UTC at 11:25:07
>   WAVEWATCH III calculating for 2022/06/06 05:30:00 UTC at 11:25:07
>   WAVEWATCH III calculating for 2022/06/06 06:00:00 UTC at 11:25:08
>   WAVEWATCH III calculating for 2022/06/06 06:30:00 UTC at 11:25:08
> application called MPI_Abort(MPI_COMM_WORLD, 21) - process 1
>   *** WAVEWATCH III ERROR IN W3IOPO :
>   LINE NUMBER         1556
>   NETCDF ERROR MESSAGE: 
>  Error: No such file or directory
>   *** WAVEWATCH III ERROR IN W3IOPO :
>   LINE NUMBER         1773
>   NETCDF ERROR MESSAGE: 
>  Error: No such file or directory
>   *** WAVEWATCH III ERROR IN W3IOPO :
>  Nonzero return at end of W3IOPON
>  Error: No such file or directory
> ```
> 
> I am investigating.

The `filename` for netCDF output appears to contain junk or is getting corrupted:
```
 CB Creating file: ./out_pnt.ww3.nc�`�
  WAVEWATCH III calculating for 2022/06/06 00:36:00 UTC at 12:40:14
  WAVEWATCH III calculating for 2022/06/06 01:12:00 UTC at 12:40:15
  WAVEWATCH III calculating for 2022/06/06 01:48:00 UTC at 12:40:15
  WAVEWATCH III calculating for 2022/06/06 02:24:00 UTC at 12:40:16
  WAVEWATCH III calculating for 2022/06/06 03:00:00 UTC at 12:40:16
```

when trying to repoen the file it gets a different filename:
```
  WAVEWATCH III calculating for 2022/06/06 06:30:00 UTC at 12:40:19
application called MPI_Abort(MPI_COMM_WORLD, 21) - process 1
 CB: Filename created: ./out_pnt.ww3.nc p�a/users/frey/WW3Git/JessicaWW3/regtests/ww3_tp2.2/work_PR1_MPI_BIN2NC/./ut_pnt.ww3.
 CB reopening file: ./out_pnt.ww3.nc p�a/users/frey/WW3Git/JessicaWW3/regtests/ww3_tp2.2/work_PR1_MPI_BIN2NC/./ut_pnt.ww3.
  *** WAVEWATCH III ERROR IN W3IOPO :
  LINE NUMBER         1558
  NETCDF ERROR MESSAGE: 
 Error: No such file or directory
```

I am not sure why this is happening at the moment.

2024-05-23 12:00 UTC, ukmo-ccbunney requested changes
TRANSFER function is causing problems in the construction of `filename`. It is resulting in non-reproducible garbage at the end of the filename.

2024-05-23 12:00 UTC, ukmo-ccbunney commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
These `TRANSFER` functions are causing filename corruption when I run on GNU (see my previous comments). If I remove the `TRANSFER` function and just build the filename with string concatenation it all works fine.

Is there a reason for the use of `TRANSFER` here? I can't see why it is needed. Could it be removed?

2024-05-23 12:47 UTC, JessicaMeixner-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@ukmo-ccbunney thank you for testing and finding this error! I'll change the way the filename is defined and have an update - hopefully by the end of the day for me, but likely tomorrow morning for you!

2024-05-23 21:02 UTC, JessicaMeixner-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@ukmo-ccbunney made an update that ran for me.  Hopefully this will work for you as well.  I just ran the one test, will start running more now.

2024-05-24 06:44 UTC, mickaelaccensi commented
I'm running the matrix. I'll keep you informed

2024-05-24 14:46 UTC, JessicaMeixner-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
Okay my tests have all looked okay.  I did find one minor update for when we use the TIMETAG.  Let me know if things do not work for you with this latest change and I'll find a different solution @ukmo-ccbunney

2024-05-24 15:43 UTC, ukmo-ccbunney commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@JessicaMeixner-NOAA - all working for me now in ww3_tp2.2.

2024-05-24 15:50 UTC, MatthewMasarik-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@JessicaMeixner-NOAA is this ready for me to test the update?

2024-05-24 15:53 UTC, JessicaMeixner-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@MatthewMasarik-NOAA Yes, this is ready for you to re-test!

2024-05-24 15:54 UTC, MatthewMasarik-NOAA commented on model/src/w3iopomd.F90
> +      filename = transfer(FNMPRE(:LEN_TRIM(FNMPRE))//TIMETAG//'out_pnt.'//FILEXT(:LEN_TRIM(FILEXT))//'.nc', filename)
@JessicaMeixner-NOAA awesome, I'll get them started!

2024-05-30 17:58 UTC, JessicaMeixner-NOAA commented
@ukmo-ccbunney @mickaelaccensi - Please let me know if you are running into any issues with this that I might be able to help with debugging.

2024-05-31 07:16 UTC, mickaelaccensi commented
matrix is done but I have both an error in develop and bin2nc branches for ww3_tp2.10 for output point processing due to the fact that the only requested output point (B45005) is considered on land. It is a SMC grid test so it is not linked to this PR. @ukmo-ccbunney and @ukmo-jianguo-li can probably double check this problem.

I've checked at ww3_tp2.2 for the format of the out_pnt.ww3.nc, it would be great to have at least the time variable defined in the correct calendar format and standard instead of a 2d array of integers. I think using the functions in w3timemd.ftn it should not bet too complicated..

Anyway, I'm now running the matrix.comp. Once done I'll keep you informed.

2024-05-31 08:26 UTC, mickaelaccensi commented
```
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
ww3_tp2.10/./work_MPI                     (1 files differ)
ww3_tp2.17/./work_mc1                     (6 files differ)
ww3_tp2.17/./work_mc                     (5 files differ)
ww3_tp2.17/./work_c                     (8 files differ)
ww3_tp2.17/./work_b                     (4 files differ)
ww3_tp2.17/./work_mb                     (3 files differ)
ww3_tp2.2/./work_PR1_MPI_BIN2NC                     (directory not found)
ww3_tp2.21/./work_b                     (6 files differ)
ww3_tp2.21/./work_mb                     (7 files differ)
ww3_tp2.6/./work_pdlib                     (14 files differ)
```

differences sound ok. tp2.17, ww2.21 and ww3_tp2.6 are due to pdlib not b4b

Except the format of time variable in out_pnt.ww3.nc, I'm ok with this PR

2024-05-31 09:53 UTC, ukmo-jianguo-li commented
This recent SMC grid update has activated an old conversion factor VSC to reverse the depth values stored in the SMC grid cell array before they are assigned to the WW3 ZB variable:

!/SMC !Li  Minimum DMIN depth is used as well for SMC.
!/SMC !!       ZB(ISEA)= - MAX( DMIN, FLOAT( IJKCel(5, ISEA) ) )
!/SMC !Li  Allow land cell to be defined by ZLIM value and only reset
!/SMC !Li  MAPST* land values for sea points.   JGLi03Nov2023
!/SMC          ZB(ISEA)= DVSMC*FLOAT( IJKCel(5, ISEA) )

The DVSMC is a copy of the VSC conversion factor, which is specified in the w3_grid.inp file on the old depth input file line:
-0.1  10.0  30   -1. 1 1 '(....)' 'NAME' 'S36125Depth.dat'
Where the fourth argument -1.(0) Is for the VSC.  This factor is not defined in the namelist input file and it results in all wet points are converted into land points.  The namelist input file in tp2.10 test needs to be updated for this factor.  If the old ww3_grid.inp file is used, it should be fine.


From: Mickael Accensi ***@***.***>
Sent: Friday, May 31, 2024 8:17 AM
To: NOAA-EMC/WW3 ***@***.***>
Cc: JianGuo Li ***@***.***>; Mention ***@***.***>
Subject: Re: [NOAA-EMC/WW3] Add option to use NetCDF output instead of binary for point output (PR #1230)


matrix is done but I have both an error in develop and bin2nc branches for ww3_tp2.10 for output point processing due to the fact that the only requested output point (B45005) is considered on land. It is a SMC grid test so it is not linked to this PR. @ukmo-ccbunney<https://github.com/ukmo-ccbunney> and @ukmo-jianguo-li<https://github.com/ukmo-jianguo-li> can probably double check this problem.

I've checked at ww3_tp2.2 for the format of the out_pnt.ww3.nc, it would be great to have at least the time variable defined in the correct calendar format and standard instead of a 2d array of integers. I think using the functions in w3timemd.ftn it should not bet too complicated..

Anyway, I'm now running the matrix.comp. Once done I'll keep you informed.

-
Reply to this email directly, view it on GitHub<https://github.com/NOAA-EMC/WW3/pull/1230#issuecomment-2141371942>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANGV3EHWHKKWZLMEAUVVJOLZFAPXFAVCNFSM6AAAAABHUSEINOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBRGM3TCOJUGI>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-05-31 10:08 UTC, mickaelaccensi commented
thanks @ukmo-jianguo-li  for the exclanation. I'll let you create an issue for this so.

2024-05-31 12:24 UTC, JessicaMeixner-NOAA commented
> Except the format of time variable in out_pnt.ww3.nc, I'm ok with this PR

@mickaelaccensi The time format is what WW3 is expecting to read in and then use in the next routines.  I'm thinking we just add an additional time variable  as you requested instead of changing this one, thoughts?

2024-06-03 08:38 UTC, ukmo-ccbunney commented
> thanks @ukmo-jianguo-li for the exclanation. I'll let you create an issue for this so.

Thanks Mickael - I'll raise an Issue for this.

2024-06-03 11:42 UTC, mickaelaccensi commented
> > Except the format of time variable in out_pnt.ww3.nc, I'm ok with this PR
> 
> @mickaelaccensi The time format is what WW3 is expecting to read in and then use in the next routines. I'm thinking we just add an additional time variable as you requested instead of changing this one, thoughts?

It seems to be a solution. To do it, you would need to rename the current time variable as another name (like time_ww3) and create a new time variable with the calendar format. It would be great for future use the out_grd.ww3.nc

2024-06-05 16:23 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi and @ukmo-ccbunney I have added the extra time variable as @mickaelaccensi requested.    Let me know what you think.  @ukmo-ccbunney I think I have addressed your concerns of things not working, but I still see changes requested, so if I missed something or things are still not working for you please let me know!

2024-06-07 15:13 UTC, mickaelaccensi commented
@JessicaMeixner-NOAA, thanks first to have added the TIME variable. There is just an issue in the TIME values. The hours are not included. see screenshot

![image](https://github.com/NOAA-EMC/WW3/assets/49198861/ed705146-4e66-4403-b88b-3c9ceabff654)

2024-06-07 15:27 UTC, JessicaMeixner-NOAA commented
Okay i just went to debug this and check this out and i somehow deleted a few lines of code.  Should have a fix here in an hour or so.  Thanks for catching this @mickaelaccensi !

2024-06-07 15:56 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi  time should be fixed now!  Please let me know if you see issues still.

2024-06-10 07:05 UTC, mickaelaccensi commented
I confirm the bugfix !

2024-06-10 07:06 UTC, mickaelaccensi approved these changes

2024-06-10 12:19 UTC, JessicaMeixner-NOAA commented
@ukmo-ccbunney - are things working for you on your end?

2024-06-11 10:07 UTC, ukmo-ccbunney approved these changes
Regression test `ww3_tp2.2/PR1_MPI_BIN2NC` ran fine and output looks good.
Running full regtest matrix now for completeness.

2024-06-12 09:26 UTC, ukmo-ccbunney commented
All regtests ran ok with just the usual differences in mww3_test_03. 👍

2024-06-12 11:48 UTC, JessicaMeixner-NOAA commented
Thanks @ukmo-ccbunney! 

@MatthewMasarik-NOAA - I think this is ready for your final review now!

2024-06-12 13:50 UTC, MatthewMasarik-NOAA commented
> Thanks @ukmo-ccbunney!
> 
> @MatthewMasarik-NOAA - I think this is ready for your final review now!

Great, thanks for confirming, I have the review in progress now.

2024-06-14 17:23 UTC, MatthewMasarik-NOAA approved these changes
**Code review**
Pass

**Testing**
Pass

* Compared with `develop` branch:
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (14 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (13 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.1/./work_unstr_b                     (1 files differ)
ww3_ufs1.1/./work_unstr_a                     (1 files differ)
ww3_ufs1.1/./work_unstr_c                     (1 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
```
[matrixCompFull.txt](https://github.com/user-attachments/files/15841404/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/15841407/matrixDiff.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/15841408/matrixCompSummary.txt)


* Compared with `feature/pointbinary2nc_hardcoded` branch:

[hardcoded.matrixCompFull.txt](https://github.com/user-attachments/files/15841412/hardcoded.matrixCompFull.txt)
[hardcoded.matrixDiff.txt](https://github.com/user-attachments/files/15841413/hardcoded.matrixDiff.txt)
[hardcoded.matrixCompSummary.txt](https://github.com/user-attachments/files/15841414/hardcoded.matrixCompSummary.txt)


Approved.

2024-06-14 17:45 UTC, merged

2024-06-14 17:57 UTC, MatthewMasarik-NOAA commented
A big thank you to @JessicaMeixner-NOAA, who took over the reins and saw this work to completion, and @edwardhartnett who initiated the work and laid the foundation.  This is a great contribution in converting WW3 binary outputs to netcdf!  Thanks also goes to @mickaelaccensi and @ukmo-ccbunney for testing, and giving feedback that improved the final PR.