Clean up and modularize build
NOAA-EMC/WW3 pull request #453
Opened 2021-08-26 12:56 UTC by JessicaMeixner-NOAA

# Pull Request Summary
This PR is a clean-up and modularization of the build. The expectation is that no answers will change. 

## Description
This PR adds a "build_utility.sh" function (copying the ideas from @arunchawla-NOAA) in preparation for cleaning up and modularizing the build before transition to CPP from switches and will help in adding additional build functionalities such as CMAKE.   Other updates include: 
* The READMEs in model/bin were consolidated to one README and additional build information such as  library dependency information was added there.  The READMES from various institutions were copied as is with the exception of formatting updates for readability. 
* The make_HYB make_MPI etc were deleted as they had not been maintained and were not 100% correct.  This will require fewer updates when moving to CPP from switches. 
* The "printer" and "C compiler" variables were removed from the wwatch3.env as the variables are not used. 
* Within the bin directory, the variable source was renamed to sterm as "source" can be a system variable. 
* The WWATCH3_NETCDF variable was removed as we only support 1 option and therefore it is no longer necessary. 

### Issue(s) addressed
* This is in prep for Issue #360 and is the last PR for the [code clean up project](https://github.com/NOAA-EMC/WW3/projects/1).  This will complete the [milestone](https://github.com/NOAA-EMC/WW3/milestone/26) for the code clean up as well. 

* Reviewers: @aliabdolali @mickaelaccensi 

### Commit Message
Clean up and modularize build

### Testing
* How were these changes tested? Regression tests
* Are the changes covered by regression tests? Yes. 
* If a new feature was added, was a new regression test added? No new features
* Have regression tests been run? yes
* Compiler / HPC used to run the regression tests in the PR: hera.intel 
* Output of matrix.comp:
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7059740/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7059741/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7059742/matrixDiff.txt)

    
* Only the expected not b4b issues: 
```
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (9 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.17/./work_mc1                     (0 files differ)
ww3_ufs1.1/./work_b                     (0 files differ)
ww3_ufs1.2/./work_b                     (0 files differ)
ww3_ufs1.3/./work_a                     (1 files differ)
```

2021-08-26 14:32 UTC, mickaelaccensi reviewed
w3_automake does not work anymore, can you check ? also some minor corrections

2021-08-26 14:32 UTC, mickaelaccensi commented on model/bin/make_makefile.sh
> +# 3.d Go through programes to create file list - - - - - - - - - - - - - - -
programs

2021-08-26 14:32 UTC, mickaelaccensi commented on model/bin/README.md
> +these are part of the Previmer system and are reported under "SHM" or "SHOM"
MARC

2021-08-26 14:32 UTC, mickaelaccensi commented on model/bin/README.md
> +these are part of the Previmer system and are reported under "SHM" or "SHOM"
LOPS

2021-08-26 14:37 UTC, JessicaMeixner-NOAA commented
> w3_automake does not work anymore, can you check ? also some minor corrections

Is w3_automake working on the top of the develop branch?  I'll try to look into why it's not working now.  I don't ever use it so I might have questions for you.  Thanks for looking and finding the other corrections!

2021-08-26 14:40 UTC, JessicaMeixner-NOAA commented on model/bin/README.md
> +these are part of the Previmer system and are reported under "SHM" or "SHOM"
So this should say instead: 
these are part of the Previmer system and are reported under "MARC" or "LOPS"

Is that correct? @mickaelaccensi

2021-08-26 16:56 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi I think I figured out what is going on with w3_automake -- it's using sort_switches which was relying on a section of make_makefile which was moved to build_utils.  I'll push updates for this after a little more testing.  I'm also going to update the list of reg vs netcdf programs because it seems a little out of date with respect to w3_make.

2021-08-26 17:25 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi w3_automake should be working now, please let me know if you have any more issues.

2021-08-26 19:57 UTC, mickaelaccensi commented on model/bin/README.md
> +these are part of the Previmer system and are reported under "SHM" or "SHOM"
these are part of the MARC system and are reported under "LOPS"

2021-08-26 20:00 UTC, mickaelaccensi commented
it works now, I'll do the regtests and keep you in touch

2021-08-27 12:46 UTC, JessicaMeixner-NOAA commented on model/bin/README.md
> +these are part of the Previmer system and are reported under "SHM" or "SHOM"
Updated -- thanks for the clarification.

2021-09-01 09:47 UTC, mickaelaccensi commented
regtests are ok except for ww3_tp2.17 which attempts to run ww3_grib by default, so I had to disable the grib output.
another error is in ww3_tr1 :
ww3_tr1/work_bndin/ww3_bound.out:IP, file, I/O error:    1, ../input_bndin/bnd1.spc,     0
ww3_tr1/work_bndin/ww3_bound.out:IP, file, I/O error:    2, ../input_bndin/bnd2.spc,     0
ww3_tr1/work_bndin/ww3_bound.out:IP, file, I/O error:    3, ../input_bndin/bnd3.spc,     0
but this one is also present in the develop branch, I'll raise an issue for this one

2021-09-07 15:33 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi the ww3_tp2.17 should be an issue for you in the develop branch too? Or is it just in this branch you have this issue?

2021-09-08 07:11 UTC, mickaelaccensi commented
it is in both develop and feature branch.

2021-09-08 11:54 UTC, JessicaMeixner-NOAA commented
> it is in both develop and feature branch.

Since it's in develop as well, I do not plan to address this in this PR then.  Is that okay @mickaelaccensi

2021-09-08 12:00 UTC, mickaelaccensi commented
ok

2021-09-09 12:30 UTC, ukmo-ccbunney requested changes
Changes look good to me.
Just a few typos.
I am running the regression test and will post the results later.

2021-09-09 12:30 UTC, ukmo-ccbunney commented on manual/impl/compile.tex
> +The following enviroment variable is also required:
typo: enviroment => environment

2021-09-09 12:30 UTC, ukmo-ccbunney commented on model/bin/README.md
> +* NetCDF-4 API enableed (Use "nc-config --has-nc4" to check)
typo: enableed => enabled.

2021-09-09 13:06 UTC, JessicaMeixner-NOAA commented on manual/impl/compile.tex
> +The following enviroment variable is also required:
Fixed!

2021-09-09 13:06 UTC, JessicaMeixner-NOAA commented on model/bin/README.md
> +* NetCDF-4 API enableed (Use "nc-config --has-nc4" to check)
fixed!

2021-09-09 13:07 UTC, JessicaMeixner-NOAA commented
Thanks for the typo corrections @ukmo-ccbunney and looking at everything, let me know if you run into any issues with the regtests.

2021-09-10 13:23 UTC, ukmo-ccbunney approved these changes
@JessicaMeixner-NOAA
Results from the regression tests on our HPC. All looks ok, apart from the usual mww3_test_03 differences and a couple of expected differences explained below:

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (11 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_ts1/./work_NL5                     (3 files differ)
ww3_tp2.17 is currently not working for me at all in develop due to some input file issues.

ww3_ts1/work_NL5 has been giving problems with other PRs (see issue #471 I just raised). However, when I re-ran that test, it came back B4B.

2021-09-10 17:35 UTC, JessicaMeixner-NOAA commented
@mickaelaccensi you have not officially approved this PR, are there any other issues you'd like me to address related to this PR?  

@thesser1 any feedback on your end?

2021-09-13 12:43 UTC, JessicaMeixner-NOAA commented
All WW3 regtests are still passing: 

[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/7154304/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/7154305/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/7154306/matrixDiff.txt)

ufs-weather-model wave tests on hera also passed

2021-09-13 13:57 UTC, aliabdolali approved these changes

2021-09-15 16:39 UTC, aliabdolali commented
I ran the tests and they all passed with pre-known non-b4b cases.

2021-09-15 16:42 UTC, merged